name: JSONPlaceholder API Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run tests daily at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:
    inputs:
      test_suite:
        description: 'Test suite to run'
        required: true
        default: 'regression'
        type: choice
        options:
          - smoke
          - regression
          - performance
          - security
          - negative

jobs:
  smoke-tests:
    name: Smoke Tests
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || contains(github.event.head_commit.message, '[smoke]')

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Run Smoke Tests
        run: mvn clean test -Psmoke

      - name: Generate Allure Report
        if: always()
        run: mvn allure:report

      - name: Upload Allure Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: smoke-test-results
          path: |
            target/allure-results/
            target/site/allure-maven-plugin/

  regression-tests:
    name: Regression Tests
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Run Regression Tests
        run: mvn clean test -Pregression

      - name: Generate Allure Report
        if: always()
        run: mvn allure:report

      - name: Upload Allure Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: regression-test-results
          path: |
            target/allure-results/
            target/site/allure-maven-plugin/

      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: target/surefire-reports/

  performance-tests:
    name: Performance Tests
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule' || contains(github.event.head_commit.message, '[performance]')

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Run Performance Tests
        run: mvn clean test -Pperformance

      - name: Generate Performance Report
        if: always()
        run: mvn allure:report

      - name: Upload Performance Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: performance-test-results
          path: |
            target/allure-results/
            target/site/allure-maven-plugin/

  security-tests:
    name: Security Tests
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule' || contains(github.event.head_commit.message, '[security]')

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Run Security Tests
        run: mvn clean test -Psecurity

      - name: Generate Security Report
        if: always()
        run: mvn allure:report

      - name: Upload Security Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: security-test-results
          path: |
            target/allure-results/
            target/site/allure-maven-plugin/

  manual-test-execution:
    name: Manual Test Execution
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Run Selected Test Suite
        run: mvn clean test -P${{ github.event.inputs.test_suite }}

      - name: Generate Allure Report
        if: always()
        run: mvn allure:report

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.inputs.test_suite }}-test-results
          path: |
            target/allure-results/
            target/site/allure-maven-plugin/

  publish-results:
    name: Publish Test Results
    runs-on: ubuntu-latest
    needs: [smoke-tests, regression-tests]
    if: always() && (needs.smoke-tests.result != 'skipped' || needs.regression-tests.result != 'skipped')

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3

      - name: Publish Test Results
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: API Test Results
          path: '**/TEST-*.xml'
          reporter: java-junit

      - name: Deploy Allure Report to GitHub Pages
        if: github.ref == 'refs/heads/main' && needs.regression-tests.result == 'success'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: regression-test-results/target/site/allure-maven-plugin/
          destination_dir: test-reports

  notify-results:
    name: Notify Test Results
    runs-on: ubuntu-latest
    needs: [smoke-tests, regression-tests, performance-tests, security-tests]
    if: always() && github.event_name == 'schedule'

    steps:
      - name: Notify Success
        if: needs.regression-tests.result == 'success'
        run: |
          echo "✅ All scheduled tests passed successfully!"

      - name: Notify Failure
        if: needs.regression-tests.result == 'failure'
        run: |
          echo "❌ Scheduled tests failed. Check the artifacts for details."
          exit 1